site_name: ETF Analytics
site_description: Documentation for ETF analytics and visualization tool
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
    - Usage: user-guide/usage.md
  - Components:
    - Analytics: components/analytics.md
    - Database: components/database.md
    - ETL Process: components/etl.md
    - Website: components/website.md
  - API Reference:
    - Database: api/database.md
    - Models: api/models.md
    - ETL: api/etl.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes

plugins:
  - search