site_name: ETF Analytics Documentation
site_description: Documentation for ETF analytics and visualization tool
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
    - How to Run Scripts: how_to_run_scripts.md
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
    - Data Verification: user-guide/verification.md
  - Components:
    - Analytics: components/analytics.md
    - Database: components/database.md
    - ETL Process: components/etl.md
    - Website: components/website.md
  - API Reference:
    - Database Manager: api/database.md
    - Data Models: api/models.md
    - ETL Pipeline: api/etl.md
    - Validators: api/validators.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - tables

plugins:
  - search