name: Daily Market Data Update

on:
  schedule:
    # Runs daily at 10 PM Berlin time (UTC+1, so 21:00 UTC)
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - automation-daily-update  # Also runs when you push to test

jobs:
  update-market-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Initialize database (if needed)
      run: |
        python analytics/database/init_db.py || echo "Database already exists"
        python analytics/database/load_symbols.py || echo "Symbols already loaded"
        
    - name: Run market data update
      run: |
        python analytics/enhanced_workflow.py --step incremental
        
    - name: Show results
      run: |
        echo "=== Database Status ==="
        python analytics/database_diagnostic.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add analytics/database/etf_database.db
        git add analytics/logs/
        git commit -m "Market data update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
