name: Deploy Website

on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 22:00 UTC (after market close) every weekday
    - cron: '0 22 * * 1-5'
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate website data
      run: |
        python -m analytics.etl.data_exporter
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website